# Generated by Django 5.2.6 on 2025-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Version for optimistic locking"
            ),
        ),
    ]
